import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

type Language = 'fr' | 'en';

interface Translations {
  nav: { home: string; services: string; expertise: string; blog: string; contact: string; quote: string; backToSite: string };
  landing: { heroTitle: string; heroSubtitle: string; ctaPrimary: string; ctaSecondary: string; expertiseTitle: string; whyTitle: string; contactTitle: string; contactSub: string; footerRights: string; rodentDesc: string; disinfectionDesc: string; insectDesc: string; featureCertified: string; featureRapid: string; featureGuarantee: string; learnMore: string; formName: string; formPhone: string; formEmail: string; formMessage: string; formSubmit: string; infoTitle: string; urgencyTitle: string; urgencyDesc: string; emergencyPhone: string };
  dashboard: { title: string; subtitle: string; scheduled: string; completed: string; pending: string; clients: string; recentActivity: string; notifications: string; viewAll: string; markRead: string; noNotifications: string; upcoming: string };
  clients: { title: string; subtitle: string; add: string; edit: string; delete: string; search: string; name: string; company: string; address: string; phone: string; email: string; confirmDelete: string; save: string; cancel: string; noClients: string; contact: string; interventionsLabel: string; completedLabel: string; scheduledLabel: string; interventionHistory: string; noInterventionsForClient: string; clientSince: string };
  interventions: { title: string; subtitle: string; add: string; edit: string; delete: string; search: string; type: string; date: string; time: string; status: string; technician: string; client: string; address: string; confirmDelete: string; scheduled: string; inProgress: string; completed: string; cancelled: string; rodent: string; disinfection: string; insect: string; noInterventions: string; all: string; detailTitle: string; unassigned: string; information: string; createdOn: string; lastModified: string; estimatedDuration: string; hours: string; select: string; titleLabel: string; cancel: string; save: string };
  technicians: { title: string; subtitle: string; add: string; edit: string; delete: string; name: string; phone: string; email: string; specialties: string; availability: string; available: string; busy: string; offDuty: string; noTechnicians: string; statTechnicians: string; statAvailable: string; statBusy: string; statOffDuty: string; interventionsLabel: string; technicianProfile: string; total: string; completedLabel: string; inProgressLabel: string; specialtiesLabel: string; noInterventionsAssigned: string; cancel: string; save: string };
  calendar: { title: string; subtitle: string; day: string; week: string; month: string };
  reports: { title: string; subtitle: string; monthly: string; byType: string; satisfaction: string; exportBtn: string; interventions: string; revenue: string };
  profile: { title: string; subtitle: string; personalInfo: string; changePassword: string; currentPassword: string; newPassword: string; confirmPassword: string; save: string; preferences: string; language: string; notifications: string; emailNotifications: string; emailNotificationsDesc: string; newInterventionNotif: string; reminderNotif: string; monthlyReportNotif: string; displayTheme: string; light: string; system: string; changeCoverPhoto: string; removeCover: string; changeProfilePhoto: string; removePhoto: string; saved: string; memberSince: string; bio: string; name: string; company: string; email: string; phone: string };
  common: { loading: string; error: string; success: string; back: string; next: string; prev: string; page: string; of: string; total: string; actions: string; status: string; noData: string; search: string; filter: string; export: string };
}

const translations: Record<Language, Translations> = {
  fr: {
    nav: { home: 'Accueil', services: 'Services', expertise: 'Expertise', blog: 'Blog', contact: 'Contact', quote: 'Devis Gratuit', backToSite: 'Retour au site' },
    landing: { heroTitle: 'Éliminez Nuisibles, Virus et Bactéries. Experts Certifiés Pour Tous.', heroSubtitle: 'Experts certifiés pour la protection de votre santé et de votre environnement.', ctaPrimary: 'Obtenir un Diagnostic Rapide', ctaSecondary: 'Découvrir nos services', expertiseTitle: 'Nos 3 Domaines d\'Expertise', whyTitle: 'Pourquoi Nous Choisir ?', contactTitle: 'Besoin d\'une Intervention ?', contactSub: 'Notre équipe vous répond sous 24h', footerRights: 'Tous droits réservés.', rodentDesc: 'Élimination complète des rongeurs avec des solutions certifiées et durables.', disinfectionDesc: 'Traitement professionnel contre les virus et bactéries. Protocoles stricts.', insectDesc: 'Traitement ciblé contre tous les insectes nuisibles. Solutions adaptées.', featureCertified: 'Produits certifiés', featureRapid: 'Intervention rapide', featureGuarantee: 'Garantie de résultat', learnMore: 'En savoir plus', formName: 'Nom complet', formPhone: 'Téléphone', formEmail: 'Email', formMessage: 'Message', formSubmit: 'Demander un Diagnostic', infoTitle: 'Informations', urgencyTitle: 'Urgence ?', urgencyDesc: 'Appelez notre ligne prioritaire', emergencyPhone: '+33 1 23 45 67 89' },
    dashboard: { title: 'Tableau de bord', subtitle: 'Vue d\'ensemble de votre activité', scheduled: 'Planifiées', completed: 'Terminées', pending: 'En attente', clients: 'Clients actifs', recentActivity: 'Activité récente', notifications: 'Notifications', viewAll: 'Voir tout', markRead: 'Marquer comme lu', noNotifications: 'Aucune notification', upcoming: 'À venir' },
    clients: { title: 'Clients', subtitle: 'Gérez vos clients', add: 'Ajouter', edit: 'Modifier', delete: 'Supprimer', search: 'Rechercher un client...', name: 'Nom', company: 'Entreprise', address: 'Adresse', phone: 'Téléphone', email: 'Email', confirmDelete: 'Confirmez-vous la suppression ?', save: 'Enregistrer', cancel: 'Annuler', noClients: 'Aucun client trouvé', contact: 'Contact', interventionsLabel: 'Interventions', completedLabel: 'Terminées', scheduledLabel: 'Planifiées', interventionHistory: 'Historique des interventions', noInterventionsForClient: 'Aucune intervention pour ce client', clientSince: 'Client depuis' },
    interventions: { title: 'Interventions', subtitle: 'Gérez vos interventions', add: 'Nouvelle intervention', edit: 'Modifier', delete: 'Supprimer', search: 'Rechercher...', type: 'Type', date: 'Date', time: 'Heure', status: 'Statut', technician: 'Technicien', client: 'Client', address: 'Adresse', confirmDelete: 'Confirmez-vous la suppression ?', scheduled: 'Planifiée', inProgress: 'En cours', completed: 'Terminée', cancelled: 'Annulée', rodent: 'Dératisation', disinfection: 'Désinfection', insect: 'Désinsectisation', noInterventions: 'Aucune intervention trouvée', all: 'Toutes', detailTitle: 'Détail de l\'intervention', unassigned: 'Non assigné', information: 'Informations', createdOn: 'Créée le', lastModified: 'Dernière modification', estimatedDuration: 'Durée estimée', hours: 'heures', select: 'Sélectionner...', titleLabel: 'Titre', cancel: 'Annuler', save: 'Enregistrer' },
    technicians: { title: 'Techniciens', subtitle: 'Gérez vos techniciens', add: 'Ajouter', edit: 'Modifier', delete: 'Supprimer', name: 'Nom', phone: 'Téléphone', email: 'Email', specialties: 'Spécialités', availability: 'Disponibilité', available: 'Disponible', busy: 'Occupé', offDuty: 'Absent', noTechnicians: 'Aucun technicien trouvé', statTechnicians: 'Techniciens', statAvailable: 'Disponibles', statBusy: 'En intervention', statOffDuty: 'Absents', interventionsLabel: 'Interventions', technicianProfile: 'Profil technicien', total: 'Total', completedLabel: 'Terminées', inProgressLabel: 'En cours', specialtiesLabel: 'Spécialités', noInterventionsAssigned: 'Aucune intervention assignée', cancel: 'Annuler', save: 'Enregistrer' },
    calendar: { title: 'Calendrier', subtitle: 'Planifiez et gérez vos interventions', day: 'Jour', week: 'Semaine', month: 'Mois' },
    reports: { title: 'Rapports', subtitle: 'Analyses et statistiques', monthly: 'Interventions par mois', byType: 'Répartition par type', satisfaction: 'Taux de satisfaction', exportBtn: 'Exporter', interventions: 'Interventions', revenue: 'Revenus (€)' },
    profile: { title: 'Profil', subtitle: 'Gérez vos informations personnelles', personalInfo: 'Informations personnelles', changePassword: 'Changer le mot de passe', currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe', confirmPassword: 'Confirmer le mot de passe', save: 'Enregistrer', preferences: 'Préférences', language: 'Langue', notifications: 'Notifications', emailNotifications: 'Notifications par email', emailNotificationsDesc: 'Recevoir les mises à jour par email', newInterventionNotif: 'Nouvelle intervention', reminderNotif: 'Rappel intervention', monthlyReportNotif: 'Rapport mensuel', displayTheme: "Thème d'affichage", light: 'Clair', system: 'Système', changeCoverPhoto: 'Changer la photo de couverture', removeCover: 'Supprimer la couverture', changeProfilePhoto: 'Changer la photo de profil', removePhoto: 'Supprimer la photo', saved: '✓ Enregistré', memberSince: 'Membre depuis', bio: 'Expert en hygiène et nuisibles depuis plus de 10 ans. Certifié biocide niveau 2.', name: 'Nom', company: 'Entreprise', email: 'Email', phone: 'Téléphone' },
    common: { loading: 'Chargement...', error: 'Erreur', success: 'Succès', back: 'Retour', next: 'Suivant', prev: 'Précédent', page: 'Page', of: 'sur', total: 'Total', actions: 'Actions', status: 'Statut', noData: 'Aucune donnée', search: 'Rechercher', filter: 'Filtrer', export: 'Exporter' },
  },
  en: {
    nav: { home: 'Home', services: 'Services', expertise: 'Expertise', blog: 'Blog', contact: 'Contact', quote: 'Free Quote', backToSite: 'Back to site' },
    landing: { heroTitle: 'Eradicate Pests, Viruses, and Bacteria. Certified Experts for Everyone.', heroSubtitle: 'Certified experts protecting your health and environment.', ctaPrimary: 'Get a Fast Diagnosis', ctaSecondary: 'Discover our services', expertiseTitle: 'Our 3 Areas of Expertise', whyTitle: 'Why Choose Us?', contactTitle: 'Need an Intervention?', contactSub: 'Our team responds within 24 hours', footerRights: 'All rights reserved.', rodentDesc: 'Complete rodent elimination with certified and lasting solutions.', disinfectionDesc: 'Professional treatment against viruses and bacteria with strict protocols.', insectDesc: 'Targeted treatment against all pests with adapted solutions.', featureCertified: 'Certified products', featureRapid: 'Rapid response', featureGuarantee: 'Guaranteed results', learnMore: 'Learn more', formName: 'Full name', formPhone: 'Phone', formEmail: 'Email', formMessage: 'Message', formSubmit: 'Request a Diagnosis', infoTitle: 'Information', urgencyTitle: 'Emergency?', urgencyDesc: 'Call our priority line', emergencyPhone: '+33 1 23 45 67 89' },
    dashboard: { title: 'Dashboard', subtitle: 'Overview of your activity', scheduled: 'Scheduled', completed: 'Completed', pending: 'Pending', clients: 'Active clients', recentActivity: 'Recent Activity', notifications: 'Notifications', viewAll: 'View all', markRead: 'Mark as read', noNotifications: 'No notifications', upcoming: 'Upcoming' },
    clients: { title: 'Clients', subtitle: 'Manage your clients', add: 'Add client', edit: 'Edit', delete: 'Delete', search: 'Search clients...', name: 'Name', company: 'Company', address: 'Address', phone: 'Phone', email: 'Email', confirmDelete: 'Confirm deletion?', save: 'Save', cancel: 'Cancel', noClients: 'No clients found', contact: 'Contact', interventionsLabel: 'Interventions', completedLabel: 'Completed', scheduledLabel: 'Scheduled', interventionHistory: 'Intervention History', noInterventionsForClient: 'No interventions for this client', clientSince: 'Client since' },
    interventions: { title: 'Interventions', subtitle: 'Manage your interventions', add: 'New intervention', edit: 'Edit', delete: 'Delete', search: 'Search...', type: 'Type', date: 'Date', time: 'Time', status: 'Status', technician: 'Technician', client: 'Client', address: 'Address', confirmDelete: 'Confirm deletion?', scheduled: 'Scheduled', inProgress: 'In Progress', completed: 'Completed', cancelled: 'Cancelled', rodent: 'Rodent Control', disinfection: 'Disinfection', insect: 'Insect Control', noInterventions: 'No interventions found', all: 'All', detailTitle: 'Intervention Details', unassigned: 'Unassigned', information: 'Information', createdOn: 'Created on', lastModified: 'Last modified', estimatedDuration: 'Estimated duration', hours: 'hours', select: 'Select...', titleLabel: 'Title', cancel: 'Cancel', save: 'Save' },
    technicians: { title: 'Technicians', subtitle: 'Manage your technicians', add: 'Add technician', edit: 'Edit', delete: 'Delete', name: 'Name', phone: 'Phone', email: 'Email', specialties: 'Specialties', availability: 'Availability', available: 'Available', busy: 'Busy', offDuty: 'Off Duty', noTechnicians: 'No technicians found', statTechnicians: 'Technicians', statAvailable: 'Available', statBusy: 'On duty', statOffDuty: 'Off duty', interventionsLabel: 'Interventions', technicianProfile: 'Technician Profile', total: 'Total', completedLabel: 'Completed', inProgressLabel: 'In Progress', specialtiesLabel: 'Specialties', noInterventionsAssigned: 'No interventions assigned', cancel: 'Cancel', save: 'Save' },
    calendar: { title: 'Calendar', subtitle: 'Plan and manage your interventions', day: 'Day', week: 'Week', month: 'Month' },
    reports: { title: 'Reports', subtitle: 'Analysis and statistics', monthly: 'Interventions per month', byType: 'Breakdown by type', satisfaction: 'Satisfaction rate', exportBtn: 'Export', interventions: 'Interventions', revenue: 'Revenue (€)' },
    profile: { title: 'Profile', subtitle: 'Manage your personal information', personalInfo: 'Personal Information', changePassword: 'Change Password', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm password', save: 'Save', preferences: 'Preferences', language: 'Language', notifications: 'Notifications', emailNotifications: 'Email notifications', emailNotificationsDesc: 'Receive updates via email', newInterventionNotif: 'New intervention', reminderNotif: 'Intervention reminder', monthlyReportNotif: 'Monthly report', displayTheme: 'Display theme', light: 'Light', system: 'System', changeCoverPhoto: 'Change cover photo', removeCover: 'Remove cover', changeProfilePhoto: 'Change profile photo', removePhoto: 'Remove photo', saved: '✓ Saved', memberSince: 'Member since', bio: 'Hygiene and pest control expert for over 10 years. Certified biocide level 2.', name: 'Name', company: 'Company', email: 'Email', phone: 'Phone' },
    common: { loading: 'Loading...', error: 'Error', success: 'Success', back: 'Back', next: 'Next', prev: 'Previous', page: 'Page', of: 'of', total: 'Total', actions: 'Actions', status: 'Status', noData: 'No data', search: 'Search', filter: 'Filter', export: 'Export' },
  },
};

interface I18nContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: Translations;
}

const I18nContext = createContext<I18nContextType | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('fr');
  const handleSetLang = useCallback((l: Language) => {
    setLang(l);
    document.documentElement.lang = l;
  }, []);

  return (
    <I18nContext.Provider value={{ lang, setLang: handleSetLang, t: translations[lang] }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useI18n() {
  const ctx = useContext(I18nContext);
  if (!ctx) throw new Error('useI18n must be used within I18nProvider');
  return ctx;
}
